# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_visual(object):
    def setupUi(self, visual):
        visual.setObjectName("visual")
        visual.resize(791, 412)
        self.label = QtWidgets.QLabel(visual)
        self.label.setGeometry(QtCore.QRect(40, 20, 91, 41))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(visual)
        self.textEdit.setGeometry(QtCore.QRect(40, 60, 711, 241))
        self.textEdit.setObjectName("textEdit")
        self.layoutWidget = QtWidgets.QWidget(visual)
        self.layoutWidget.setGeometry(QtCore.QRect(60, 330, 671, 30))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.check = QtWidgets.QPushButton(self.layoutWidget)
        self.check.setObjectName("check")
        self.horizontalLayout.addWidget(self.check)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.trans = QtWidgets.QPushButton(self.layoutWidget)
        self.trans.setObjectName("trans")
        self.horizontalLayout.addWidget(self.trans)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.git = QtWidgets.QPushButton(self.layoutWidget)
        self.git.setObjectName("git")
        self.horizontalLayout.addWidget(self.git)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.close = QtWidgets.QPushButton(self.layoutWidget)
        self.close.setObjectName("close")
        self.horizontalLayout.addWidget(self.close)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.clear = QtWidgets.QPushButton(self.layoutWidget)
        self.clear.setObjectName("clear")
        self.horizontalLayout.addWidget(self.clear)
        self.label_2 = QtWidgets.QLabel(visual)
        self.label_2.setGeometry(QtCore.QRect(250, 380, 361, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(visual)
        self.label_3.setGeometry(QtCore.QRect(320, 10, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")

        self.retranslateUi(visual)
        QtCore.QMetaObject.connectSlotsByName(visual)

    def retranslateUi(self, visual):
        _translate = QtCore.QCoreApplication.translate
        visual.setWindowTitle(_translate("visual", "可视化"))
        self.label.setText(_translate("visual", "控制台提示："))
        self.check.setText(_translate("visual", "配置环境"))
        self.trans.setText(_translate("visual", "转换代码"))
        self.git.setText(_translate("visual", "克隆Git"))
        self.close.setText(_translate("visual", "关闭"))
        self.clear.setText(_translate("visual", "清空屏幕"))
        self.label_2.setText(_translate("visual", "注意：请先克隆项目，再配置环境，最后转换代码"))
        self.label_3.setText(_translate("visual", "可视化配置工具"))
