name: svf-example

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-11]
    steps:
      # checkout the repo
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
          
      # setup the environment 
      - name: mac-setup
        if: runner.os == 'macOS'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 12.5.1
      - name: mac-setup-workaround
        if: runner.os == 'macOS'
        run: ln -sfn /Applications/Xcode_12.5.1.app /Applications/Xcode.app
      - name: ubuntu-setup
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install cmake gcc g++ nodejs doxygen graphviz python3
          
      # install llvm and svf
      - name: env-setup
        run: |
          npm install svf-lib
          
      # build current repo
      - name: build-svf
        run: |
         source $GITHUB_WORKSPACE/env.sh
         cmake .
         make 
         clang -S -c -g -fno-discard-value-names -emit-llvm example.c -o example.ll
         python3 ./src/svf-ex.py example.ll

