name: svf-example

# Triggers the workflow on push or pull request events
on: 
  [ push, pull_request, repository_dispatch]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      XCODE_VERSION: '15.3.0'
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      # checkout the repo
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          
      # setup the environment 
      - name: mac-setup
        if: runner.os == 'macOS'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}
      - name: mac-setup-workaround
        if: runner.os == 'macOS'
        run: ln -sfn /Applications/Xcode_${{ env.XCODE_VERSION }}.app /Applications/Xcode.app
      - name: ubuntu-setup
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install cmake gcc g++ nodejs doxygen graphviz
          
      # install llvm and svf
      - name: env-setup
        run: |
          npm install svf-lib
          
      # build current repo
      - name: build-svf
        run: |
         source $GITHUB_WORKSPACE/env.sh
         cmake .
         make 
