name: svf-example

# Triggers the workflow on push or pull request events
on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]
    steps:
      # checkout the repo
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      # setup the environment 
      - name: env-setup
        run: |
          npm install svf-lib
          if [ "$RUNNER_OS" = "Linux" ]; then sudo apt-get update       ; fi
          if [ "$RUNNER_OS" = "Linux" ]; then sudo apt-get install cmake gcc g++; fi

      - name: build-svf
        run: |
         source $GITHUB_WORKSPACE/env.sh
         cmake .
         make 
         curl -o $GITHUB_WORKSPACE/curl.bc 'https://github.com/SVF-tools/Test-Suite/blob/master/test_cases_bc/crux-bc/curl.bc'
         $GITHUB_WORKSPACE/bin/svf-ex -pt-type=cbv $GITHUB_WORKSPACE/curl.bc
