name: svf-example

on:
  push:
  pull_request:
  repository_dispatch:
    types: [new-commit-from-SVF]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      XCODE_VERSION: "15.3.0"
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    steps:
      # checkout the repo
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # setup the environment
      - name: mac-setup
        if: runner.os == 'macOS'
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ env.XCODE_VERSION }}
      - name: mac-setup-workaround
        if: runner.os == 'macOS'
        run: ln -sfn /Applications/Xcode_${{ env.XCODE_VERSION }}.app /Applications/Xcode.app
      - name: ubuntu-setup
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
          sudo apt-get update
          sudo apt-get install cmake gcc g++ nodejs doxygen graphviz
          sudo apt-get install -y build-essential cmake gcc g++ nodejs doxygen graphviz git curl software-properties-common lcov libncurses5-dev libtinfo6 libzstd-dev libffi-dev zlib1g-dev

      # install llvm and svf
      - name: env-setup
        run: |
          npm install svf-lib

      # build current repo
      - name: build-svf-example
        run: |
          export SVF_DIR=$(npm root)/SVF
          export LLVM_DIR=$(npm root)/llvm-16.0.0.obj
          export Z3_DIR=$(npm root)/z3.obj
          cmake -B build -S ./ --install-prefix=$GITHUB_WORKSPACE/preinstall_svf
          cmake --build build --verbose
          cmake --install build --verbose

      - name: build-svf-from-scratch
        run: |
          git clone https://github.com/SVF-tools/SVF.git
          cd SVF
          source build.sh
          cd ..
          cmake -B scratch_build -S ./ --install-prefix=$GITHUB_WORKSPACE/scratch_svf
          cmake --build scratch_build --verbose
          cmake --install scratch_build --verbose
